#!/bin/sh

# personal aliases 

alias ll='ls -Gla'

OS=`uname | tr '[:upper:]' '[:lower:]'`
if [ "$OS" == "Darwin" ]; then
	alias ls='ls -G'
fi

alias blog="cd ${HOME}/Dropbox/blog"
alias sl='open -a "Sublime Text 2"'

## Aliases
alias grep='grep --color'
