#!/bin/bash

OS=`uname | tr '[:upper:]' '[:lower:]'`
if [ "$OS" == "Darwin" ]; then
	alias ls='ls -G'
fi

function mf() {
	unzip -p $1 META-INF/MANIFEST.MF
}

## Aliases
alias ll='ls -Gla'
alias grep='grep --color'

alias mf=mf

alias java8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`"
alias java11="export JAVA_HOME=`/usr/libexec/java_home -v 11`"
alias java14="export JAVA_HOME=`/usr/libexec/java_home -v 14`"

## Personal Aliases 
alias blog="cd ${HOME}/Dropbox/blog"
alias httpserv='python -m SimpleHTTPServer'

## docker Aliases 

alias dk-rmi-unused='docker rmi $(docker images -a -q --filter=dangling=true)'
